# Generated by Django 3.2.8 on 2021-10-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211017_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='robotcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
