# Generated by Django 3.2.8 on 2021-10-17 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20211017_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='auth.user'),
            preserve_default=False,
        ),
    ]
